AWSTemplateFormatVersion: 2010-09-09
Description: ALB stack


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General configuration 
        Parameters:
          - Environment

      - Label:
          default: ALB configuration 
        Parameters:
          - ALBName
          - ALBSecurityGroup
          - ALBPublicSubnetIds
          - ALBHostedZoneId
          - ALBDomainName

      - Label:
          default: Target configuration 
        Parameters:
          - TargetGroupVpcId
          - TargetInstanceIds
          - TargtGroupHealthCheckPath


Parameters:
  Environment:
    Description: |
      Choose the environment.
      Default is Dev.
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - QA
      - Prod

  ALBName:
    Description: Enter aplication load balancer name. 
    Type: String

  ALBSecurityGroup:
    Description: Select appliction load balancer security group id
    Type: AWS::EC2::SecurityGroup::Id

  ALBPublicSubnetIds:
    Description: Enter a valid public subnet ids
    Type: List<AWS::EC2::Subnet::Id>

  ALBHostedZoneId:
    Description: |
      Enter a dns zone id. E.g. Z07311111111111111U5I.
      You can find it using the command
      "aws route53 list-hosted-zones | grep -E '(Name|Id)'"
    Type: String

  ALBDomainName:
    Description: Enter a domain name for ALB.
    Type: String
    Default: mysh.cloud

  TargetGroupVpcId:
    Description: Select a target vpc. 
    Type: AWS::EC2::VPC::Id

  TargetInstanceIds:
    Description: List of the target instance ids.
    Type: List<String>

  TargtGroupHealthCheckPath:
    Description: Path of health check. Default is "/".
    Type: String
    Default: '/'


Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      Type: application
      IpAddressType: ipv4
      Name: !Ref ALBName
      Scheme: internet-facing 
      SecurityGroups: [!Ref ALBSecurityGroup]
      Subnets: !Ref ALBPublicSubnetIds
      Tags: 
        - Key: Name
          Value: !Sub ${Environment}-ALB

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: ApplicationLoadBalancer
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: !Ref TargtGroupHealthCheckPath
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200-299
      Port: 80
      Protocol: HTTP
      VpcId: !Ref TargetGroupVpcId
      TargetType: instance
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 20
      Targets:
        - Id: !Select [0, !Ref TargetInstanceIds]
          Port: 80
        - Id: !Select [1, !Ref TargetInstanceIds]
          Port: 80

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - RedirectConfig:
            Host: "#{host}"
            Path: "/#{path}"
            Port: 443
            Protocol: HTTPS
            Query: "#{query}"
            StatusCode: HTTP_301
          Type: redirect
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

  ALBListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref ALBListenerCertificate

  ALBListenerCertificate: 
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Ref ALBDomainName 
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref ALBDomainName
          HostedZoneId: !Ref ALBHostedZoneId
      Tags:
        - Key: Name
          Value: !Sub ${ALBDomainName}-Certificate


Outputs:
  ALBDnsName:
    Value: !GetAtt ApplicationLoadBalancer.DNSName 
    Export:
      Name: !Sub ${AWS::StackName}::ALBDnsName

  ALBCanonicalHostedZoneID:
    Value: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
    Export:
      Name: !Sub ${AWS::StackName}::ALBCanonicalHostedZoneID
