AWSTemplateFormatVersion: 2010-09-09
Description: ECR repository


Parameters:
  Environment:
    Description: Choose the environment.
    Type: String
    Default: Dev
    AllowedValues: [Dev, QA, Prod]

  ImageTagMutability:
    Description: IMMUTABLE | MUTABLE
    Default: MUTABLE
    Type: String
    AllowedValues:
      - IMMUTABLE
      - MUTABLE

  ImageScanOnPush:
    Default: false 
    Type: String
    AllowedValues:
      - true 
      - false

  RepositoryName:
    Description: If Environment is set to Dev, then repository name would be dev-RepositoryName
    Type: String
    Default: spring-books-api


Mappings:
  Environment:
    Dev:
      lowercase: !Sub dev-${RepositoryName}
    QA:
      lowercase: qa 
    Prod:
      lowercase: prod 


Resources:
  Repository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Join ['-', !FindInMap [Environment, !Ref Environment, lowercase], !Ref RepositoryName]
      ImageTagMutability: !Ref ImageTagMutability
      ImageScanningConfiguration:
        ScanOnPush: !Ref ImageScanOnPush
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only one untagged image, expire all others",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "imageCountMoreThan",
                  "countNumber": 1
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-ECR-${RepositoryName}
        - Key: Environment 
          Value: !Ref Environment


Outputs:
  RepositoryName:
    Value: !Ref Repository
    Export:
      Name: !Sub ${AWS::StackName}::RepositoryName

  RepositoryArn:
    Value: !GetAtt Repository.Arn
    Export:
      Name: !Sub ${AWS::StackName}::RepositoryArn

  RepositoryUri:
    Value: !GetAtt Repository.RepositoryUri
    Export:
      Name: !Sub ${AWS::StackName}::RepositoryUri
