AWSTemplateFormatVersion: 2010-09-09
Description: ECS cluster, task definition, service, logs, iam role


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General configuration 
        Parameters:
          - Environment

      - Label:
          default: Cluster configuration 
        Parameters:
          - ClusterName 

      - Label:
          default: Task configuration 
        Parameters:
          - RepositoryUri
          - DBSecretArn
          - ImageTag
          - SsmDBName
          - ContainerPort 

      - Label:
          default: Service configuration 
        Parameters:
          - SubnetA
          - SubnetB
          - SecurityGroup
          - TargetGroupArn


Parameters:
  Environment:
    Description: Choose the environment.
    Type: String
    Default: Dev
    AllowedValues: [Dev, QA, Prod]

  ImageTag:
    Default: 0.0.1
    Type: String

  RepositoryName:
    Type: String
    Default: spring-books-api

  ClusterName:
    Type: String
    Default: skillup-cluster

  RepositoryUri:
    Type: String
    Description: 426711337666.dkr.ecr.eu-central-1.amazonaws.com/spring-books-api

  DBSecretArn:
    Type: String

  SsmDBName:
    Type: String

  ContainerPort:
    Type: Number 

  SubnetA:
    Type: AWS::EC2::Subnet::Id

  SubnetB:
    Type: AWS::EC2::Subnet::Id

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id

  TargetGroupArn:
    Type: String

  DesiredCapacity:
    Description: Desired containers count 
    Type: Number
    Default: 2


Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName 
      CapacityProviders: [FARGATE, FARGATE_SPOT]
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-ECS-Cluster
        - Key: Environment 
          Value: !Ref Environment

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 512
      Memory: 1024 
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: !Ref RepositoryName
          Image:  !Join [':', [!Ref RepositoryUri, !Ref ImageTag]]
          Cpu: 0
          Essential: true
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
          Secrets:
            - Name: DB_USERNAME
              ValueFrom: !Sub '${DBSecretArn}:username::'
            - Name: DB_PASSWORD
              ValueFrom: !Sub '${DBSecretArn}:password::'
            - Name: DB_HOST 
              ValueFrom: !Sub '${DBSecretArn}:host::'
            - Name: DB_PORT
              ValueFrom: !Sub '${DBSecretArn}:port::'
            - Name: DB_NAME
              ValueFrom: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${SsmDBName}
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-ECS-TaskDefinition-${RepositoryName}
        - Key: Environment 
          Value: !Ref Environment

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['/', [/ecs, !Ref Environment, !Ref RepositoryName]]
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-ECS-LogGroup-${RepositoryName}
        - Key: Environment 
          Value: !Ref Environment

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref ClusterName, ExecutionRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: secrets-ro-policy
          PolicyDocument: 
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - "secretsmanager:GetRandomPassword"
                  - "secretsmanager:GetResourcePolicy"
                  - "secretsmanager:GetSecretValue"
                  - "secretsmanager:DescribeSecret"
                  - "secretsmanager:ListSecretVersionIds"
                  - "secretsmanager:ListSecrets"
                Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*
        - PolicyName: ssm-ro-policy
          PolicyDocument: 
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - "ssm:GetParameters"
                  - "ssm:GetParameter"
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-ECS-Role
        - Key: Environment 
          Value: !Ref Environment

  Service:
    Type: AWS::ECS::Service
    Properties: 
      ServiceName: !Ref RepositoryName
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: !Ref DesiredCapacity
      LaunchType: FARGATE
      NetworkConfiguration: 
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref SecurityGroup
      LoadBalancers:
        - ContainerName: !Ref RepositoryName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroupArn
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-ECS-Service-${ClusterName}
        - Key: Environment 
          Value: !Ref Environment


Outputs:
  ClusterName:
    Value: !Ref Cluster
    Export:
      Name: !Sub ${AWS::StackName}::ClusterName

  ClusterArn:
    Value: !GetAtt Cluster.Arn
    Export:
      Name: !Sub ${AWS::StackName}::ClusterArn

  TaskDefinitionArn:
    Value: !Ref TaskDefinition
    Export:
      Name: !Sub ${AWS::StackName}::TaskDefinitionArn

  LogGroupName:
    Value: !Ref LogGroup
    Export:
      Name: !Sub ${AWS::StackName}::LogGroupName

  LogGroupArn:
    Value: !GetAtt LogGroup.Arn
    Export:
      Name: !Sub ${AWS::StackName}::LogGroupArn

  ExecutionRoleName:
    Value: !Ref ExecutionRole 
    Export:
      Name: !Sub ${AWS::StackName}::ExecutionRoleName

  ExecutionRoleArn:
    Value: !GetAtt ExecutionRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}::ExecutionRoleArn

  ExecutionRoleId:
    Value: !GetAtt ExecutionRole.RoleId
    Export:
      Name: !Sub ${AWS::StackName}::ExecutionRoleId

  ServiceArn:
    Value: !Ref Service 
    Export:
      Name: !Sub ${AWS::StackName}::ServiceArn

  ServiceName:
    Value: !GetAtt Service.Name
    Export:
      Name: !Sub ${AWS::StackName}::ServiceName
