AWSTemplateFormatVersion: 2010-09-09
Description: Root stack that brings all stacks together.


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment parameters
        Parameters:
          - Environment
          - TemplatesBucketURL 

      - Label:
          default: VPC parameters
        Parameters:
          - VPCCidr
          - PublicSubnetCidr
          - PrivateDBSubnet01Cidr
          - PrivateDBSubnet02Cidr

      - Label:
          default: Server parameters
        Parameters:
          - InstanceType

      - Label:
          default: RDS parameters
        Parameters:
          - DBIdentifier
          - DBInstanceType
          - DBMasterUser
          - DBMasterPassword
          - DBStorage
          - DBEngine


Parameters:
  Environment:
    Description: |
      Choose the environment.
      Default is Dev.
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - QA
      - Prod

  TemplatesBucketURL:
    Description: |
      Specify the s3 bucket where the CF templates are located.
      Default is https://s3.amazonaws.com/mysh-cf-templates
    Type: String
    Default: https://s3.amazonaws.com/mysh-cf-templates

  ####################### VPC stack parameters #######################

  VPCCidr:
    Description: |
      Enter VPC CIDR block.
      Default is 192.168.88.0/26
    Type: String
    Default: 192.168.88.0/26

  PublicSubnetCidr:
    Description: |
      Enter public subnet CIDR block.
      Default is 192.168.88.0/28
    Type: String
    Default: 192.168.88.0/28 

  PrivateDBSubnet01Cidr:
    Description: |
      Enter private DB subnet CIDR block.
      Default is 192.168.88.32/28
    Type: String
    Default: 192.168.88.32/28 

  PrivateDBSubnet02Cidr:
    Description: |
      Enter private DB subnet CIDR block.
      Default is 192.168.88.48/28
    Type: String
    Default: 192.168.88.48/28 

  ##################### Server stack parameters ######################

  InstanceType:
    Description: |
      Select EC2 instance type.
      Default is t2.micro.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t4g.small
      - t2.micro
      - t3.micro

  ####################### RDS stack parameters #######################

  DBIdentifier:
    Description: RDS identifier
    Type: String
    Default: database
    AllowedPattern: '[a-zA-Z0-9\-]*'
    ConstraintDescription: Must contain only alphanumeric characters and dashes [a-zA-Z0-9\-]

  DBInstanceType:
    Description: |
      Choose the database instance type.
      Default is db.t3.micro.
    Type: String
    Default: db.t3.micro
    AllowedValues:
      - db.t3.micro
      - db.t2.micro

  DBMasterUser:
    Description: Enter a valid Database master username.
    Type: String
    Default: admin

  DBMasterPassword:
    Description: Enter a valid Database master password.
    Type: String
    NoEcho: true
    MinLength: 16
    MaxLength: 32

  DBStorage:
    Description: |
      The amount of database storage in gibibytes (GiB).
      Default is 20.
    Type: String
    Default: 20

  DBEngine:
    Description: |
      Select database engine.
      Default is mysql-8.0.28.
    Type: String
    Default: mysql-8.0.28
    AllowedValues:
      - mysql-8.0.28
      - mysql-5.7.42
      - postgres-11.20
      - postgres-12.14
      - postgres-12.14
      - postgres-13.11
      - postgres-14.8
      - postgres-15.3


Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplatesBucketURL}/vpc.yaml
      Parameters:
        Environment: !Ref Environment
        VPCCidr: !Ref VPCCidr
        PublicSubnetCidr: !Ref PublicSubnetCidr
        PrivateDBSubnet01Cidr: !Ref PrivateDBSubnet01Cidr
        PrivateDBSubnet02Cidr: !Ref PrivateDBSubnet02Cidr
 
  SecurityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplatesBucketURL}/security.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        DBEngine: !Select [0, !Split ['-', !Ref DBEngine]]

  ServerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplatesBucketURL}/server.yaml
      Parameters:
        Environment: !Ref Environment
        InstanceType: !Ref InstanceType
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        WebSecurityGroupId: !GetAtt SecurityStack.Outputs.WebSecurityGroupId

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplatesBucketURL}/database.yaml
      Parameters:
        DBIdentifier: !Ref DBIdentifier
        DBInstanceType: !Ref DBInstanceType
        DBMasterUser: !Ref DBMasterUser
        DBMasterPassword: !Ref DBMasterPassword
        DBStorage: !Ref DBStorage
        DBEngine: !Ref DBEngine
        DBSubnetIds: 
          Fn::Join:
            - ','
            - - !GetAtt VPCStack.Outputs.PrivateDBSubnet01Id
              - !GetAtt VPCStack.Outputs.PrivateDBSubnet02Id
        DBSecurityGroupId: !GetAtt SecurityStack.Outputs.DBSecurityGroupId
