AWSTemplateFormatVersion: 2010-09-09
Description: DNS stack 


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: ALB alias configuration 
        Parameters:
          - ALBDnsName
          - ALBCanonicalHostedZoneID
          - ALBHostedZoneId
          - ALBDomainName


Parameters:
  ALBDnsName:
    Description: ALB AWS DNS Name
    Type: String

  ALBCanonicalHostedZoneID:
    Description:
      The ID of the Route53 hosted zone associated with the load balancer
    Type: String

  ALBHostedZoneId:
    Description: |
      Enter a dns zone id. E.g. Z07311111111111111U5I.
      You can find it using the command
      "aws route53 list-hosted-zones | grep -E '(Name|Id)'"
    Type: String

  ALBDomainName:
    Type: String
    Default: mysh.cloud


Resources:
  MyshCloudRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref ALBHostedZoneId
      RecordSets:
        - Name: !Ref ALBDomainName 
          Type: A
          AliasTarget:
            HostedZoneId: !Ref ALBCanonicalHostedZoneID
            DNSName: !Ref ALBDnsName 
