AWSTemplateFormatVersion: 2010-09-09
Description: DNS stack 


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: ALB alias configuration 
        Parameters:
          - ALBDnsName
          - ALBHostedZoneId
          - ALBDomainName
          - ALBCanonicalHostedZoneID

      - Label:
          default: Jenkins records 
        Parameters:
          - Jenkins01Ip


Parameters:
  ALBDnsName:
    Description: ALB AWS DNS Name
    Type: String

  ALBHostedZoneId:
    Description: |
      Select a dns zone ids. 
    Type: AWS::Route53::HostedZone::Id

  ALBDomainName:
    Type: String
    Default: mysh.cloud

  ALBCanonicalHostedZoneID:
    Description:
      The ID of the Route53 hosted zone associated with the load balancer
    Type: String

  Jenkins01Ip:
    Type: String

Resources:
  MyshCloudRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref ALBHostedZoneId
      RecordSets:
        - Name: !Ref ALBDomainName 
          Type: A
          AliasTarget:
            HostedZoneId: !Ref ALBCanonicalHostedZoneID
            DNSName: !Ref ALBDnsName 
        - Name: !Sub jenkins-01.${ALBDomainName}
          ResourceRecords:
            - !Ref Jenkins01Ip
          Type: A
          TTL: 300
