AWSTemplateFormatVersion: 2010-09-09
Description: DNS stack 


Parameters:
  ALBDnsName:
    Description: ALB DNS Name
    Type: String

  ALBCanonicalHostedZoneID:
    Description:
      The ID of the Route53 hosted zone associated with the load balancer
    Type: String

  ALBHostedZoneId:
    Description: |
      Enter a dns zone id. E.g. Z07311111111111111U5I.
      You can find it using the command "aws route53 list-hosted-zones"
    Type: String

  ALBDomainName:
    Type: String
    Default: mysh.cloud


Resources:
  MyshCloudRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref ALBHostedZoneId
      RecordSets:
        - Name: !Ref ALBDomainName 
          Type: A
          AliasTarget:
            HostedZoneId: !Ref ALBCanonicalHostedZoneID
            DNSName: !Ref ALBDnsName 
