AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket with life cycle policy


Parameters:
  BucketName:
    Description: Enter S3 bucket name
    Type: String
    MinLength: 8
    MaxLength: 32
    AllowedPattern: "[a-z0-9-]+" 


Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      LifecycleConfiguration:
        Rules:
          - Id: Rule for log prefix
            Prefix: logs
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
            ExpirationInDays: 365


Outputs:
  s3BucketNameOutput:
    Value: !Ref S3Bucket
