AWSTemplateFormatVersion: 2010-09-09
Description: Create Secutiry Group


Parameters:
  Environment:
    Description: |
      Choose the environment.
      Default is Dev.
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - QA
      - Prod

  VpcId:
    Type: AWS::EC2::VPC::Id

  DBEngine:
    Type: String


Conditions:
  IsDBEngineMySQL: !Equals [!Ref DBEngine, mysql]


Resources:
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: !Sub ${Environment} Web server security group
      GroupName: !Sub ${Environment}WebSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup 
          Description: Allow HTTP only to ALB
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref ALBSecurityGroup 
          Description: Allow HTTPS
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: Allow SSH
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow outbound traffic to all destinations
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-Web-SG

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: !Sub ${Environment} application load balancer security group
      GroupName: !Sub ${Environment}ALBSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: Allow HTTP
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-ALB-SG

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: !Sub ${Environment} database security group
      GroupName: !Sub ${Environment}DBSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !If
            - IsDBEngineMySQL
            - 3306
            - 5432
          ToPort: !If
            - IsDBEngineMySQL
            - 3306
            - 5432
          SourceSecurityGroupId: !Ref WebSecurityGroup
          Description: Allow connection to all web sg
      SecurityGroupEgress:
        - IpProtocol: -1
          DestinationSecurityGroupId: !Ref WebSecurityGroup
          Description: Allow outbound traffic only to web sg 
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-DB-SG


Outputs:
  WebSecurityGroupId:
    Value: !Ref WebSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}::WebSecurityGroupId

  ALBSecurityGroupId:
    Value: !Ref ALBSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}::ALBSecurityGroupId

  DBSecurityGroupId:
    Value: !Ref DBSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}::DBSecurityGroupId
