AWSTemplateFormatVersion: 2010-09-09
Description: EC2 instances stack


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General configuration 
        Parameters:
          - Environment

      - Label:
          default: Instance networking
        Parameters:
          - PublicSubnetIds
          - SubnetAvailabilityZones
          - WebSecurityGroupId

      - Label:
          default: Instance configuration 
        Parameters:
          - LatestAmiId
          - InstanceType
          - KeyPair


Parameters:
  Environment:
    Description: |
      Choose the environment.
      Default is Dev.
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - QA
      - Prod

  InstanceType:
    Description: |
      Select EC2 instance type.
      Default is t2.micro.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t4g.small
      - t2.micro
      - t3.micro

  LatestAmiId:
    Description: |
      Enter SSM Parameter for AMI.
      Default is /aws/service/debian/release/11/latest/amd64
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/debian/release/11/latest/amd64

  PublicSubnetIds:
    Description: Enter a valid public subnet ids
    Type: List<AWS::EC2::Subnet::Id>

  SubnetAvailabilityZones:
    Description: Enter a public subnet availability zones in the same order.
    Type: List<AWS::EC2::AvailabilityZone::Name>

  WebSecurityGroupId:
    Description: Enter a valid web security group id
    Type: AWS::EC2::SecurityGroup::Id

  KeyPair:
    Description: EC2 Key Pair to access the server
    Type: AWS::EC2::KeyPair::KeyName


Resources:
  WebInstance01:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType 
      ImageId: !Ref LatestAmiId
      AvailabilityZone: !Select [0, !Ref SubnetAvailabilityZones]
      SubnetId: !Select [0, !Ref PublicSubnetIds]
      SecurityGroupIds: [!Ref WebSecurityGroupId]
      KeyName: !Ref KeyPair
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-Web-01

  WebInstance02:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType 
      ImageId: !Ref LatestAmiId
      AvailabilityZone: !Select [1, !Ref SubnetAvailabilityZones]
      SubnetId: !Select [1, !Ref PublicSubnetIds]
      SecurityGroupIds: [!Ref WebSecurityGroupId]
      KeyName: !Ref KeyPair
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-Web-02


Outputs:
  WebInstance01Id:
    Value: !Ref WebInstance01
    Export:
      Name: !Sub ${AWS::StackName}::WebInstance01Id

  WebInstance02Id:
    Value: !Ref WebInstance02
    Export:
      Name: !Sub ${AWS::StackName}::WebInstance02Id

  WebInstanceIds:
    Value: !Join
      - ','
      - - !Ref WebInstance01
        - !Ref WebInstance02
    Export:
      Name: !Sub ${AWS::StackName}::WebInstanceIds
