AWSTemplateFormatVersion: 2010-09-09
Description: SQS Standard Queue


Parameters:
  Environment:
    Description: |
      Choose the environment.
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - QA
      - Prod

  DelaySeconds:
    Description: |
        The time in seconds that the delivery of all messages in the queue is delayed.
        You can specify an integer value of 0 to 900 (15 minutes).
    Default: '5'
    Type: Number

  MaximumMessageSize:
    Description: |
      The limit of how many bytes that a message can contain before Amazon SQS rejects it,
      1024 bytes (1 KiB) to 262144 bytes (256 KiB)
    Default: 262144
    Type: Number

  MessageRetentionPeriod:
    Description: |
      The number of seconds that Amazon SQS retains a message.
      You can specify an integer value from 60 seconds (1 minute) to 1209600 seconds (14 days).
    Type: Number
    Default: 345600

  ReceiveMessageWaitTimeSeconds:
    Description: |
      Specifies the duration, in seconds, that the ReceiveMessage action call waits
      until a message is in the queue in order to include it in the response,
      as opposed to returning an empty response if a message is not yet available. 0 to 20
    Type: Number
    Default: 0

  CreateDeadLetterQueue:
    Description: |
      A dead-letter queue is a queue that other (source) queues can target for messages 
      that can't be processed (consumed) successfully. 
      You can set aside and isolate these messages in the dead-letter queue 
      to determine why their processing doesn't succeed.
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  VisibilityTimeout:
    Description: |
      This should be longer than the time it would take to process and delete a message,
      this should not exceed 12 hours.
    Type: Number
    Default: 5


Conditions:
  CreateDeadLetterQueue: !Equals
    - !Ref CreateDeadLetterQueue
    - true


Resources:
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Environment}-Queue
      DelaySeconds: !Ref DelaySeconds
      MaximumMessageSize: !Ref MaximumMessageSize
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
      ReceiveMessageWaitTimeSeconds: !Ref ReceiveMessageWaitTimeSeconds
      RedrivePolicy:
        Fn::If:
          - CreateDeadLetterQueue
          - deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
            maxReceiveCount: 5
          - !Ref AWS::NoValue
      VisibilityTimeout: !Ref VisibilityTimeout
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-Queue
        - Key: Environment 
          Value: !Ref Environment

  DeadLetterQueue:
    Condition: CreateDeadLetterQueue
    Type: AWS::SQS::Queue
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-Queue
        - Key: Environment 
          Value: !Ref Environment


Outputs:
  QueueURL:
    Description: URL of newly created SQS Queue
    Value: !Ref SQSQueue
    Export:
      Name: !Sub ${AWS::StackName}::QueueURL

  QueueARN:
    Description: ARN of newly created SQS Queue
    Value: !GetAtt SQSQueue.Arn
    Export:
      Name: !Sub ${AWS::StackName}::QueueARN

  QueueName:
    Description: Name newly created SQS Queue
    Value: !GetAtt SQSQueue.QueueName
    Export:
      Name: !Sub ${AWS::StackName}::QueueName

  DeadLetterQueueURL:
    Condition: CreateDeadLetterQueue
    Description: URL of the dead letter queue
    Value: !Ref DeadLetterQueue
    Export:
      Name: !Sub ${AWS::StackName}::DeadLetterQueueURL

  DeadLetterQueueARN:
    Condition: CreateDeadLetterQueue
    Description: ARN of the dead letter queue
    Value: !GetAtt DeadLetterQueue.Arn
    Export:
      Name: !Sub ${AWS::StackName}::DeadLetterQueueARN
