AWSTemplateFormatVersion: 2010-09-09
Description: Step functions state machine


Parameters:
  TopicArn:
    Description: SNS Topic ARN
    Type: String

  QueueUrl:
    Description: SQS Queue URL
    Type: String


Resources:
  StepFunctionStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString:
        !Sub |
          {
            "Comment": "A state machine that automates a call center support session.",
            "StartAt": "ProcessTransaction",
            "States": {
              "ProcessTransaction": {
                "Type": "Choice",
                "Choices": [
                  {
                    "Variable": "$.TransactionType",
                    "StringEquals": "PURCHASE",
                    "Next": "ProcessPurchase"
                  },
                  {
                    "Variable": "$.TransactionType",
                    "StringEquals": "REFUND",
                    "Next": "ProcessRefund"
                  }
                ]
              },
              "ProcessRefund": {
                "Comment": "Broadcast to SNS",
                "Type": "Task",
                "Resource": "arn:aws:states:::sns:publish",
                "Parameters": {
                  "TopicArn": "${TopicArn}",
                  "Message": {
                    "TransactionId.$": "$.TransactionId",
                    "TransactionType.$": "$.TransactionType"
                  }
                },
                "End": true
              },
              "ProcessPurchase": {
                "Comment": "Broadcast to SQS",
                "Type": "Task",
                "Resource": "arn:aws:states:::sqs:sendMessage",
                "Parameters": {
                  "QueueUrl": "${QueueUrl}",
                  "MessageBody": {
                    "TransactionId.$": "$.TransactionId",
                    "TransactionType.$": "$.TransactionType"
                  }
                },
                "End": true
              }
            }
          }
      RoleArn: !GetAtt StepFunctionExecutionRole.Arn

  StepFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionAccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "sqs:SendMessage"
                  - "sns:Publish"
                Resource: "*"


Outputs:
  StateMachineArn:
    Value: !Ref StepFunctionStateMachine
    Export:
      Name: !Sub ${AWS::StackName}::StateMachineArn
