AWSTemplateFormatVersion: 2010-09-09
Description: Create VPC (1 public subnet, 1 private subnet)


Parameters:
  Environment:
    Description: |
      Choose the environment.
      Default is Dev.
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - QA 
      - Prod

  VPCCidr:
    Description: |
      Enter VPC CIDR block.
      Default is 192.168.88.0/26
    Type: String
    Default: 192.168.88.0/26

  PublicSubnet01Cidr:
    Description: |
      Enter public subnet 01 CIDR block.
      Default is 192.168.88.0/28
    Type: String
    Default: 192.168.88.0/28 

  PublicSubnet02Cidr:
    Description: |
      Enter public subnet 02 CIDR block.
      Default is 192.168.88.16/28
    Type: String
    Default: 192.168.88.16/28 

  PrivateDBSubnet01Cidr:
    Description: |
      Enter private DB subnet CIDR block.
      Default is 192.168.88.32/28
    Type: String
    Default: 192.168.88.32/28 

  PrivateDBSubnet02Cidr:
    Description: |
      Enter private DB subnet CIDR block.
      Default is 192.168.88.48/28
    Type: String
    Default: 192.168.88.48/28 


Resources:
  VPC:
    Type: AWS::EC2::VPC   
    Properties:
      CidrBlock: !Ref VPCCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags: 
        - Key: Name
          Value: !Sub ${Environment}-VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: !Sub ${Environment}-IG

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      VpcId: !Ref VPC 
      InternetGatewayId: !Ref InternetGateway 

  ####################### public subnets #######################

  PublicSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Ref PublicSubnet01Cidr
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub ${Environment}-PublicSubnet01

  PublicSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Ref PublicSubnet02Cidr
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub ${Environment}-PublicSubnet02

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC 
      Tags: 
      - Key: Name
        Value: !Sub ${Environment}-RouteTable

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref PublicRouteTable
      GatewayId: !Ref InternetGateway
    DependsOn:
      - VPCGatewayAttachment

  PublicSubnetRouteTableAssociation01:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet01

  PublicSubnetRouteTableAssociation02:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet02

  ####################### private subnets #######################

  PrivateDBSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Ref PrivateDBSubnet01Cidr
      Tags:
      - Key: Name
        Value: !Sub ${Environment}-DB-PrivateSubnet01

  PrivateDBSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Ref PrivateDBSubnet02Cidr
      Tags:
      - Key: Name
        Value: !Sub ${Environment}-DB-PrivateSubnet02


Outputs:
  VpcId:
    Value: !Ref VPC
    Export:
      Name: !Sub ${AWS::StackName}::VpcId

  VpcCidr:
    Value: !GetAtt VPC.CidrBlock
    Export:
      Name: !Sub ${AWS::StackName}::VpcCidr

  PublicSubnet01Id:
    Value: !Ref PublicSubnet01
    Export:
      Name: !Sub ${AWS::StackName}::PublicSubnet01Id

  PublicSubnet02Id:
    Value: !Ref PublicSubnet02
    Export:
      Name: !Sub ${AWS::StackName}::PublicSubnet02Id

  PrivateDBSubnet01Id:
    Value: !Ref PrivateDBSubnet01
    Export:
      Name: !Sub ${AWS::StackName}::PrivateDBSubnet01Id

  PrivateDBSubnet02Id:
    Value: !Ref PrivateDBSubnet02
    Export:
      Name: !Sub ${AWS::StackName}::PrivateDBSubnet02Id
